### PR TITLE
Zoned storage blog

### PR DESCRIPTION
**Pull request by roybotbot**
blog that'll go up tomorrow, Feb 22

### CODE REVIEW

**Review by jmhands — APPROVED** [review]
looks good!

**Review by hoffmang9 — APPROVED** [review]
Other than making sure we know what we're doing with the `date:   2021-11-06 04:00:33` e.g., this looks good.

**Review by hoffmang9 — APPROVED** [review]
AOK

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Pull request merged**
